### PR TITLE
key concepts

### PR DESCRIPTION
**Pull request by vabarbosa**
#60

### CODE REVIEW

**Review by lornajane — CHANGES_REQUESTED** [review]
If this is all the editing we need to this area, then I think we should remove the comments.  Plenty of users will view markdown as text.

**Comment by vabarbosa** [comment]
@lornajane comments removed

**Review by isc-rsingh — COMMENTED** [review]
change "Data stays safe on your device" to "Data stays reliably on your device" (I expect security/encryption features when I see the word safe)

change Persistance to Persistence (a to e)

**Comment by vabarbosa** [comment]
@rajrsingh updated

**Pull request merged**
